"""
Open-loop Feeder Node for Week 2 using cflib.
Reads 'optimal_trajectory.csv' generated by trajectory_optimizer.py
and blindly sends position setpoints to the simulated Crazyflie.
"""

import time
import csv
import sys
import cflib.crtp
from cflib.crazyflie import Crazyflie
from cflib.crazyflie.syncCrazyflie import SyncCrazyflie

DEFAULT_URI = 'tcp://127.0.0.1:5760'  # Standard crazyflie/gazebo simulation URI

def read_trajectory(filename):
    trajectory = []
    try:
        with open(filename, 'r') as f:
            reader = csv.DictReader(f)
            for row in reader:
                trajectory.append({
                    't': float(row['t']),
                    'x': float(row['x']),
                    'y': float(row['y']),
                    'z': float(row['z']),
                    'vx': float(row['vx']),
                    'vy': float(row['vy']),
                    'vz': float(row['vz'])
                })
        return trajectory
    except FileNotFoundError:
        print(f"Error: Could not find {filename}. Did you run trajectory_optimizer.py first?")
        sys.exit(1)

def execute_trajectory(scf, trajectory):
    print("Unlocking thrust...")
    scf.cf.commander.send_setpoint(0, 0, 0, 0)
    time.sleep(0.1)

    print("Taking off to 1.03 m height...")
    # Gentle takeoff to starting position
    start_pt = trajectory[0]
    takeoff_time = 3.0
    steps = 30
    for i in range(steps):
        z_target = (i / float(steps)) * start_pt['z']
        scf.cf.commander.send_position_setpoint(start_pt['x'], start_pt['y'], z_target, 0)
        time.sleep(takeoff_time / steps)

    print("Executing optimal trajectory blindly! (Open-Loop)")
    start_time = time.time()
    idx = 0
    n_points = len(trajectory)
    
    while idx < n_points:
        now = time.time() - start_time
        target_t = trajectory[idx]['t']
        
        # If the real time caught up to the next waypoint in our trajectory schedule
        if now >= target_t:
            pt = trajectory[idx]
            # Send the position setpoint at this exact moment
            scf.cf.commander.send_position_setpoint(pt['x'], pt['y'], pt['z'], 0)
            idx += 1
        else:
            time.sleep(0.01) # Slight sleep to prevent maxing out CPU loop
            
    print("Trajectory complete. Holding position for 2 seconds...")
    end_pt = trajectory[-1]
    for _ in range(20):
        scf.cf.commander.send_position_setpoint(end_pt['x'], end_pt['y'], end_pt['z'], 0)
        time.sleep(0.1)
        
    print("Landing...")
    for i in range(steps):
        z_target = end_pt['z'] * (1.0 - (i / float(steps)))
        scf.cf.commander.send_position_setpoint(end_pt['x'], end_pt['y'], z_target, 0)
        time.sleep(takeoff_time / steps)
    
    scf.cf.commander.send_stop_setpoint()
    print("Done!")

if __name__ == '__main__':
    uri = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_URI
    
    print("Initializing crazyflie drivers...")
    cflib.crtp.init_drivers()
    trajectory = read_trajectory('optimal_trajectory.csv')
    
    print(f"Connecting to Crazyflie at {uri} ...")
    try:
        with SyncCrazyflie(uri, cf=Crazyflie(rw_cache='./cache')) as scf:
            execute_trajectory(scf, trajectory)
    except Exception as e:
        print(f"Failed to connect or execute trajectory: {e}")
        print("\nMake sure your Gazebo simulation is running using 'ign gazebo crazyflie_world.xml' first, and that the cflib plugin exposes the URI.")
